version: "3.8"
services:
  localstack:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localstack:4566/health"]
      interval: 2s
      timeout: 5s
      retries: 20
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3:4566
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localhost
      - DEFAULT_REGION=us-east-2
  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - localstack
    volumes:
      - ./test_data:/test_data
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-2
    entrypoint: /bin/bash -c
    command: >
      '
        until curl http://localstack:4566/health; do
          echo "Waiting for localstack";
          sleep 1;
        done;
        aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket web-bucket --region us-east-1
        aws --endpoint-url=http://localstack:4566 s3 cp /test_data/hello.js s3://web-bucket/reports/
        aws --endpoint-url=http://localstack:4566 s3 cp /test_data/index.css s3://web-bucket/reports/
        aws --endpoint-url=http://localstack:4566 s3 cp /test_data/index.html s3://web-bucket/reports/
      '
